"""aded users to chores and todo  list


Revision ID: 43db8ada751f
Revises: d09b8110bd3a
Create Date: 2024-03-30 13:44:35.812911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43db8ada751f'
down_revision = 'd09b8110bd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chores_user_id_users_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_todo_list_user_id_users_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
