"""empty message

Revision ID: 7f5c9aed03d5
Revises: 43db8ada751f
Create Date: 2024-03-30 18:43:15.535528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5c9aed03d5'
down_revision = '43db8ada751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_server')
    op.drop_table('_alembic_tmp_todo_list')
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('repeat_time', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('repeat_time')
        batch_op.drop_column('repeat')

    op.create_table('_alembic_tmp_todo_list',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=300), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('date_entered', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_todo_list_user_id_users_id')
    )
    op.create_table('email_server',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server', sa.VARCHAR(length=100), nullable=True),
    sa.Column('port', sa.VARCHAR(length=100), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
