"""empty message

Revision ID: 83adfe141582
Revises: 
Create Date: 2024-03-24 01:24:35.640954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83adfe141582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=300), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('date_entered', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
